# Generated by Django 3.1.7 on 2021-04-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('weather', models.TextField()),
                ('max_temp', models.SmallIntegerField()),
                ('min_temp', models.SmallIntegerField()),
                ('unit_type', models.CharField(max_length=1)),
            ],
        ),
    ]
